# Generated by Django 3.2.8 on 2021-10-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_hero_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('txt_1', models.TextField()),
                ('txt_2', models.TextField()),
                ('txt_3', models.TextField(blank=True)),
                ('html', models.CharField(max_length=5)),
                ('css', models.CharField(max_length=5)),
                ('python', models.CharField(max_length=5)),
                ('graphic', models.CharField(max_length=5)),
            ],
        ),
    ]
