# Generated by Django 3.2.8 on 2021-10-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_services_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=50)),
                ('exp', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('award', models.CharField(max_length=50)),
            ],
        ),
    ]
